fix: modify lighthouserc.js url

diff --git a/.github/workflows/lighthouse-demo.yml b/.github/workflows/lighthouse-demo.yml
--- a/.github/workflows/lighthouse-demo.yml
+++ b/.github/workflows/lighthouse-demo.yml
@@ -15,7 +15,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2 # 在剛剛 run on 字段指定的 ubuntu 執行環境中抓取我們專案的程式碼
+      uses: actions/checkout@v3 # 在剛剛 run on 字段指定的 ubuntu 執行環境中抓取我們專案的程式碼
 
     - name: Install Node.js
       uses: actions/setup-node@v1
@@ -24,12 +24,12 @@ jobs:
 
     - name: npm install, build
       run: |
-          yarn
+          npm install
           npm run build
 
     - name: run lighthouse-ci
       run: |
-          npm install -g @lhci/cli
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          npm install -g @lhci/cli@0.12.x
+          lhci autorun || echo "LHCI failed!"
       env:
         LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
